config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :battles, only: [:new, :create, :edit, :update]
  root to: "battles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
# frozen_string_literal: true

class Battle < ApplicationRecord
  has_many :competitions, dependent: :destroy
  has_many :pastries, through: :competitions
  has_many :employees, through: :pastries

  accepts_nested_attributes_for :competitions

  validates :date, presence: true
end

app/models/competition.rb
# frozen_string_literal: true

class Competition < ApplicationRecord
  belongs_to :pastry
  belongs_to :battle
  belongs_to :employee, optional: true

  delegate :name, to: :pastry, prefix: true
  delegate :name, to: :employee, prefix: true
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  validates :name, presence: true
  belongs_to :pastry
end

app/models/pastry.rb
# frozen_string_literal: true

class Pastry < ApplicationRecord
  validates :name, presence: true

  has_many :employees, dependent: :destroy
  has_many :competitions, dependent: :destroy
  has_many :battles, through: :competitions, dependent: :destroy
end

app/models/selection.rb
# frozen_string_literal: true

class Selection < ApplicationRecord
  belongs_to :pastry
  belongs_to :battle
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/battles_controller.rb
# frozen_string_literal: true

class BattlesController < ApplicationController
  def index
    @battles = Battle.includes(:pastries)
  end

  def new
    @battle = Battle.new
    @next_monday = date_of_next('Monday')
  end

  def create
    battle = Battle.create!(date: date_of_next('Monday'))
    battle.pastry_ids = params[:battle][:pastry_ids]
    battle.save!
    redirect_to root_path
  end

  def edit
    @battle = battle
  end

  def update
    params[:battle][:competitions_attributes].each do |comp_params|
      Competition
        .find(comp_params.last[:id])
        .update(employee: Employee.find(comp_params.last[:employee_id]))
    end
    redirect_to root_path
  end

  private

  def battle
    Battle.find(params[:id])
  end

  def date_of_next(day)
    date = Date.parse(day)
    delta = date > Time.zone.today ? 0 : 7
    date + delta
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/battles/edit.html.erb
<h1>Interface: Chief Happiness Officer</h1>

<h1>Edit Battle N°: <%= @battle.id %></h1>
  <p>Date: <%= @battle.date %></p>
  <%= simple_form_for @battle, url: battle_path(@battle), method: :put do |f| %>

    <%= f.fields_for :competitions do |competition_form| %>
      <%= competition_form.association :employee, label: competition_form.object.pastry.name, collection: competition_form.object.pastry.employees, id: "#{rand}" %>
    <% end %>

  <%= f.button :submit, value: 'Mettre à jour la bataille' %>
  <hr>
<% end %>

app/views/battles/index.html.erb
<h1>Toutes les batailles(<%= @battles.size %>)</h1>
<%= link_to 'Ajouter une nouvelle bataille', new_battle_path %>
<hr>
<ul>
  <% @battles.each do |battle| %>
  <li>
    Date: <%= battle.date %>
    <ol>
    <% battle.competitions.each do |competition| %>
      <p>
        <li>
          <%= competition.pastry_name %>: <%= competition.employee.nil? ? '-' : competition.employee_name %>
        </li>
      </p>
    <% end %>
    </ol>
    <p>
      <%= link_to 'Ajouter les cuistos', edit_battle_path(battle) %>
    </p>
  </li>
  <hr>
  <% end %>
</ul>

app/views/battles/new.html.erb
<h1>Interface du Grand Chef Cuisto Linguini</h1>

<p>Prochain lundi: <%= @next_monday %></p>

<%= simple_form_for @battle do |f| %>
  <%= f.association :pastries, as: :check_boxes, label: 'Pâtisserie' %>
  <%= f.button :submit, value: 'Créer une bataille' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PastryFight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>